### ISSUE TITLE
Changes to version 0.9 Aditional Artists Variables usage ?

### ISSUE THREAD

**Issue by ghost** [rdswift/picard-plugins#7]
Hi
Firstly thank you for providing these great Picard plugins.

I have been using the Additional Artists Variables plugin for some time now but have spotted some weirdness after upgrading to 0.9. My scripts (which I think I lifted directly from one of your forum posts) as follows:

`$set(albumartist,%_artists_album_primary_std%))`
`$set(artist,%_artists_album_primary_std%))`

I have an album by Bill Evans which features Stan Getz, previously both Artist and AlbumArtist were set to Bill Evans (as desired) but under 0.9 both are set to Stan Getz.

Has the context changed under 0.9 ?

**Comment by rdswift** [comment]
I don't think anything should have changed.  What album is giving you the problems?  A link or an MBID to the release in question would be great so that I can do some testing with the same album.

Thanks.

**EDIT:**  I took a look and the only album I could find that showed Bill Evans and Stan Getz as the album artists is [Stan Getz & Bill Evans](https://musicbrainz.org/release-group/1e435c68-d824-3ca2-8498-6d0eacdb6c36) which lists Stan Getz first which would put him as the primary album artist.  The closest I could find to what you describe is [But Beautiful](https://musicbrainz.org/release-group/0c28b6c2-8f9c-3a98-88af-f85ce7f0cdda), but this is by Bill Evans Trio featuring Stan Getz which would put "Bill Evans Trio" as the primary album artist (not "Bill Evans").  To further complicate things, one of the releases in this release group show the album artist as "Stan Getz with Bill Evans Trio" which would show "Stan Getz" as the primary album artist.

**Comment by ghost** [comment]
Hi
Yes, it was Bill Evans Trio But Beautiful which on 0.8 lists as Bill Evans Trio (sorry for any confusion I caused there) I can see how different releases could confuse things further.

I have 65 Bill Evans / Bill Evans Trio albums in my collection all of which report the primary artist / albumartist as either Bill Evans or Bill Evans Trio under 0.8. Under 0.9 11 albums are reported with the secondary artist as primary.

A couple more examples;
Bill Evans Trio - Crosscurrents MBID b7761e42-b7e9-4451-8690-23416d77a3e1 (Reports primary as Warne Marsh)
Bill Evans - Affinity MBID 4297ba98-f6bc-4d5d-9a9e-7a5b6253430b (Reports as Toots Thielemans)

Thanks for looking at this

**Comment by rdswift** [comment]
There was indeed a bug.  Thanks for pointing this out!

I have [submitted the correction](https://github.com/metabrainz/picard-plugins/pull/371) to the "official" plugins, but until it has been accepted and the web site updated the updated plugin can be downloaded [from my repo](https://github.com/rdswift/picard-plugins/raw/2.0_RDS_Plugins/plugins/additional_artists_variables/additional_artists_variables.zip) and installed manually.
